version: "3"

services:
  app:
    container_name: DBZAPI
    restart: always
    build: .
    ports:
      - "2345:2345"
      - "4000:4000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: grankaiosama
    #   MONGO_INITDB_ROOT_PASSWORD: zUryolMPgyIyQ1Py
